package ar.com.cgarcete.demo.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import ar.com.cgarcete.demo.domain.Person;
import ar.com.cgarcete.demo.service.PersonService;
import ar.com.cgarcete.demo.utils.Log;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class PersonRestController {
	
	// This means to get the bean called subscriberRepository
    // Which is auto-generated by Spring, we will use it to handle the data
	@Autowired
	private PersonService personService;

	@GetMapping(path="/all")
	public @ResponseBody Iterable<Person> getAllPersons() {
		Log.info("GET ALL PERSONS - ");
		return personService.findAll();
	}
	
	@GetMapping("/{id}")
	public ResponseEntity<?> findById(@PathVariable("id") Long id) {
		Log.info("GET ONE PERSON -");
		Person person = personService.findOne(id);
		
		return ResponseEntity.ok().body(person.toString());
	}
	
	@PostMapping
	public ResponseEntity<?> save(@RequestBody Person subscriber) {
		Log.info("POST - "	+	subscriber.toString());
		personService.save(subscriber);
		return ResponseEntity.ok().body("Created person: "+ subscriber.toString());

	}
}
