package ar.com.cgarcete.demo.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;


import ar.com.cgarcete.demo.domain.Subscriber;
import ar.com.cgarcete.demo.repository.SubscriberRepository;


@Controller    // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class SubscriberRestController {

	@Autowired
	private SubscriberRepository subscriberRepository;// This means to get the bean called subscriberRepository
    // Which is auto-generated by Spring, we will use it to handle the data

	@GetMapping(path="/all")
	public @ResponseBody Iterable<Subscriber> getAllUsers() {
		// This returns a JSON or XML with the users
		return subscriberRepository.findAll();
	}
}
